server:
  port: 8081
  servlet:
    context-path: /subscription-service

spring:
  application:
    name: subscription-service
  profiles:
    active: local

  # ================================
  # KAFKA CONFIGURATION
  # ================================
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 5
      properties:
        enable.idempotence: true
    consumer:
      group-id: subscription-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.ecommerce.platform"

# ================================
# CUSTOM APPLICATION PROPERTIES
# ================================
app:
  subscription:
    billing-cycles: MONTHLY,QUARTERLY,YEARLY
    grace-period-days: 7
    max-retry-attempts: 3
    default-currency: BRL
    billing:
      retry-interval-hours: 24
      past-due-notification-days: 1,3,7
      auto-cancel-after-days: 30
  integration:
    order-service:
      url: http://localhost:8080
      timeout: 5000ms
    payment-service:
      url: http://localhost:8082
      timeout: 5000ms
    notification-service:
      url: http://localhost:8084
      timeout: 3000ms
  kafka:
    topics:
      subscription-events: subscription.events
      billing-events: billing.events
      order-events: order.events
      payment-events: payment.events