spring:
  datasource:
    url: jdbc:h2:mem:subscriptiondb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  quartz:
    job-store-type: memory
    jdbc:
      initialize-schema: never

  cache:
    type: none

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always
    quartz:
      enabled: false

logging:
  level:
    com.ecommerce.platform: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"