spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  cache:
    type: none

  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}